### ISSUE TITLE
The game can't start because of voxygen panicked

### ISSUE THREAD

**Issue by lumingzh** [flathub/net.veloren.veloren#42]
The log file below:

[2022-03-10_voxygen.log](https://github.com/flathub/net.veloren.veloren/files/8219849/2022-03-10_voxygen.log)

**Comment by tim77** [comment]
Thanks for reporting. But latest version of Veloren works fine for me. Same GPU as your - 3060 but desktop, not mobile. Please file a bug upstream and provide more information like distro, full specs, DE, drivers version.

https://book.veloren.net/players/reporting-bugs.html
