### ISSUE TITLE
Consider Shuttering This Package

### ISSUE THREAD

**Issue by saadatxyz** [flathub/net.veloren.veloren#45]
I would like to ask the maintainers to consider shuttering this package to help remove confusion as to what is the official package on Flathub.

Example of such confusion is seen [here](https://www.reddit.com/r/linux_gaming/comments/w6s477/veloren_fresh_release_but_both_flatpak_and_snap/).

**Comment by tim77** [comment]
Consider shuttering such kind of ignorant proposals. This is bugtracker, not Reddit talks. I don't read Reddit. Such kind of discussions MUST be discussed only with upstream and proper place. All various builds have their pros and cons. `net.veloren.veloren` the only one which can give guaranty that it will work on end user machine. Flathub maintainers and Veloren devs can't fix your graphic drivers or OS issues. Every update of `net.veloren.veloren` works on my machine and couple of other people which using it regularly. If something need to be fixed you should file bug properly or send patch with fix. This open source. The only problem with `net.veloren.veloren` that when it not updated in timely manner then you can't connect to **official** server. This is doesn't mean game doesn't work. And again feel free to send PR with fix next time when it failed to build from source.
