### ISSUE TITLE
veloren-voxygen crashed

### ISSUE THREAD

**Issue by Doomsdayrs** [flathub/net.veloren.veloren#55]
[veloren.log.txt](https://github.com/flathub/net.veloren.veloren/files/10045403/veloren.log.txt)

**Comment by tim77** [comment]
> What should I do?

We need your help to fix this! You can help by contacting us and reporting this problem. To do this, open an issue on the Veloren issue tracker:

https://www.gitlab.com/veloren/veloren/issues/new
